### ISSUE TITLE
多标签页同时传输同一个文件时遇到了问题

### ISSUE THREAD

**Issue by qiuai** [tmplink/tmplink_webapp#111]
开了2个标签页传输同一个文件来增加上传速度时，遇到了问题
1.一个标签页显示完成，但另外一个标签页仍在传输文件
![image](https://user-images.githubusercontent.com/1404171/177442130-e239b614-e19e-4f41-ac9b-b2d8ba71844e.png)

2.未完成传输的标签页一直有文件传输但不会更新传输进程了，刷新后会在目录下得到一个正在传输的文件。
![image](https://user-images.githubusercontent.com/1404171/177442030-34f366f8-df4b-445e-b17d-d576c4fc7e40.png)

**Comment by tmplink** [comment]
此问题已被解决。
