### ISSUE TITLE
New Feature Request: 将选择的特定文件项目在线打包后下载

### ISSUE THREAD

**Issue by Yanlin-Duanmu** [tmplink/tmplink_webapp#118]
背景：文件夹中有多个文件，而且文件数量较多。对于不同的访问者来说，需求并不相同，往往只是选择其中一些，而且对于图片类需要进行预览，再进行下载的选择。预览的需要和用户下载需求的不同，导致不适用于提前打包好再上传。

问题：如果只是单纯的选择特定文件并选择下载，目前并不会打包成压缩文件，而是会一个个下载，且无法打断。
对于电脑用户，需要指定文件存放位置时，会不断弹出下载框，有多少个文件就要确认多少次。如果允许默认下载，那就会直接散在download文件夹中。
对于手机用户来说，遇到的问题类似，而且批量下载文件比电脑用户的体验更不友好些。

请求：请问是否可以添加进行在线打包成压缩文件的功能，方便用户进行下载？

**Comment by tmplink** [comment]
打包下载是计划中的功能，由于需要非常多的服务器资源，目前等待规模达到一定程度才有办法进行支持。
在此之前：

1，对于自动分类到特定文件夹，可以考虑这个插件。
https://sspai.com/post/44486

2，对于批量下载的另外一个办法，就是生成下载链接，然后复制粘贴到下载软件中（创建任务前指定存储的文件夹）。

**Comment by Yanlin-Duanmu** [comment]
非常感谢回复，我会尝试您建议的方法。

另外，请问是否有考虑过调用JSZip？JSZip允许直接在浏览器中生成zip，同时可以避免占用服务器资源。对总体积不大、下载数量未破千的下载内容采取这种措施也许是一个可行项。
JSZip: https://stuk.github.io/jszip/

期待打包下载功能的早日实现，祝您开发顺利，bug少少  ; )

**Comment by tmplink** [comment]
基于最新的浏览器 API，现已实现打包下载的功能。无需调用 Zip。

**Comment by tmplink** [comment]
我们的目标是打造无需客户端的在线存储系统。
这个项目其实从 2010 年就开始了，已经等了很多年了~
