### ISSUE TITLE
Question: 是否会根据IP地域判断下载是否需要登录？

### ISSUE THREAD

**Issue by Yanlin-Duanmu** [tmplink/tmplink_webapp#119]
测试环境：未登录的浏览器（核心为Android Webview 83.0） 国内IP 国外IP 从tmp.link、ttttt.link分享出同一文件夹的对应域名链接

测试结果：
tmp.link站点：国外可以直接下载无需登录  国内访问失败
ttttt.link站点：国外可以直接下载无需登录  国内未登录时下载弹窗提示需要登录才可以下载

疑问：网站是否会根据IP地域判断下载是否需要登录？设置这样的限制是有什么特殊原因吗

**Comment by tmplink** [comment]
确实有，中国大陆地区的下载会有额外的规则和限制。原因应该不用多说吧？
要避开这些规则提供纯粹的下载，请使用直链。

**Comment by Yanlin-Duanmu** [comment]
明白，那是否意味国外IP上传的文件在被国内IP下载时仍然会受到当地律法的内容审查？
感谢您的回复。

**Comment by tmplink** [comment]
关于这两个问题：

1，无论在哪里上传的文件，都需要在遵守当地法律的情况下进行文件分享。
请查阅服务条款：https://ttttt.link/?tmpui_page=/tos

2，钛盘官方不会主动去审查您上传的文件。
请查阅隐私政策：https://ttttt.link/?tmpui_page=/privacy

**Comment by Yanlin-Duanmu** [comment]
好的，谢谢回复
