### ISSUE TITLE
文件列表存在重名文件时全选再单选只会匹配到第一个同名文件

### ISSUE THREAD

**Issue by kslr** [tmplink/tmplink_webapp#99]
需要使用 id 或者 hash 来定位

**Comment by tmplink** [comment]
无法复现此问题，可否提供一个动态图或者视频？
关于定位的实现，一直都是使用 id 来定位的，具体代码可参考这个文件。
https://github.com/tmplink/TMP_tmpUI/blob/master/js/core/tools_file_manager.js#L31
